name: movie_task_app


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  sqflite: ^2.3.3+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  sqflite_common_ffi: ^2.3.3



flutter:
  uses-material-design: true

  assets:
    - assets/images/
